// TYPE
export const MAIN_REFRESH = 'MAIN_REFRESH';

export const DAILYCASES_LOADING = 'DAILYCASES_LOADING';
export const DAILYCASES_LOADING_FAILED = 'DAILYCASES_LOADING_FAILED';
export const DAILYCASES_LOADING_SUCCESS = 'DAILYCASES_LOADING_SUCCESS';


export const CASESSTAT_LOADING = 'CASESSTAT_LOADING';
export const CASESSTAT_LOADING_FAILED = 'CASESSTAT_LOADING_FAILED';
export const CASESSTAT_LOADING_SUCCESS = 'CASESSTAT_LOADING_SUCCESS';



export const API_SERVICE = 'http://192.168.100.52:9090/api/v1'
export const CASESINFO_API = API_SERVICE + '/CasesInfo';
export const CASESSUM_API = API_SERVICE + '/CasesSum';
export const CASESSTAT_API = API_SERVICE + '/CasesStatistics';
export const DAILYCASES_API = API_SERVICE + '/dailyCases';
